$(document).ready(function(){
    $(".btn-link").click(function(){
      $('#change-img').attr('src','images/white.webp');
    });
  });
  $(document).ready(function(){
    $(".btn-dark").click(function(){
      $('#change-img').attr('src','images/black.webp');
    });
  });
  $(document).ready(function(){
    $(".btn-primary").click(function(){
      $('#change-img').attr('src','images/blue.webp');
    });
  });
  $(document).ready(function(){
    $(".grey").click(function(){
      $('#change-img').attr('src','images/grey.webp');
    });
  });
  $(document).ready(function(){
    $(".btn-danger").click(function(){
      $('#change-img').attr('src','images/red.webp');
    });
  });
  $(document).ready(function(){
    $("#btn1").click(function(){
      $('#change-img').attr('src','images/in.webp');
    });
  });
  $(document).ready(function(){
    $("#btn2").click(function(){
      $('#change-img').attr('src','images/interior.webp');
    });
  });