$(document).ready(function(){
    $(".btn-link").click(function(){
      $('#change-img').attr('src','images/white.jpg');
    });
  });
  $(document).ready(function(){
    $(".btn-dark").click(function(){
      $('#change-img').attr('src','images/black.jpg');
    });
  });
  $(document).ready(function(){
    $(".btn-primary").click(function(){
      $('#change-img').attr('src','images/blue.jpg');
    });
  });
  $(document).ready(function(){
    $(".grey").click(function(){
      $('#change-img').attr('src','images/grey.jpg');
    });
  });
  $(document).ready(function(){
    $(".btn-danger").click(function(){
      $('#change-img').attr('src','images/red.jpg');
    });
  });
  $(document).ready(function(){
    $("#btn1").click(function(){
      $('#change-img').attr('src','images/in white.webp');
    });
  });
  $(document).ready(function(){
    $("#btn2").click(function(){
      $('#change-img').attr('src','images/in black.webp');
    });
  });